name: flame_bubble_pop
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  flame: ^1.8.0
  cupertino_icons: ^1.0.8
  flame_svg: ^1.11.11
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bubble.png
    - assets/images/pop.png
    - assets/images/background.png
    - assets/images/musician.svg
    - assets/images/forecaster.svg

